var myInteger = 99;
var myDecimal = 99.999;
var myString = "99.999999";
var myEmptyString = "";
var myBoolean = true;
var myExponential = 99e-3;
var myUndefined1;
var myUndefined2 = undefined;
var myNull = null;
console.log("Integer: " + myInteger);
console.log("Decimal: " + myDecimal);
console.log("Boolean: " + myBoolean);
console.log("Empty String: " + myEmptyString);
console.log("String: " + myString);
console.log("Exponential: " + myExponential);
console.log("Undefined1: " + myUndefined1);
console.log("Undefined2: " + myUndefined2);
console.log("Null: " + myNull);
console.log("Undefined == Null: " + (myUndefined1 == myNull));
console.log("Undefined === Null: " + (myUndefined1 === myNull));

